const source = 'https://education.lego.com/en-us/product-resources/mindstorms-ev3/teacher-resources/scratch-how-to-videos/';
const video = (id, token) => `https://legoeducation.23video.com/v.ihtml/player.html?autoMute=0&autoPlay=0&photo_id=${id}&source=embed&token=${token}`;
export const lessons = [
  { id:'start', title:'Tu primer robot EV3', label:'Primeros pasos', time:'20 min', color:'blue', video:video('38679803','be317c7f090b8b10cb3168d74006d790'), source, summary:'Conoce el entorno de programación y prepara tu EV3.', steps:['Identifica el ladrillo EV3, sus motores A–D y las entradas 1–4.', 'Revisa la carga y prepara una superficie despejada.', 'Mira el video de LEGO; muestra su entorno original. Esta aula usa JavaScript.', 'Conecta el EV3 y ejecuta el saludo y tono del proyecto inicial.'], challenge:'Cambia el mensaje y la frecuencia del tono; explica qué hace await.' },
  { id:'motors', title:'Movimiento con motores', label:'Programación', time:'30 min', color:'orange', video:video('38679792','4d722cffdb1fadd689767d32c4619fae'), source, summary:'Experimenta con dirección, velocidad y duración.', steps:['Mira el video de motores EV3; compara sus bloques con las instrucciones del editor.', 'Conecta un motor grande o mediano al puerto A.', 'En el editor, inserta Motor y ejecuta await robot.motor("A", 30, 1000).', 'Cambia 30 por -30 para invertir el sentido. La duración está en milisegundos y cada orden está limitada a 10 segundos.'], challenge:'Programa tres movimientos con una pausa de un segundo entre ellos.' },
  { id:'touch', title:'Responde al contacto', label:'Sensores', time:'20 min', color:'green', video:video('38679798','d56e314463a37aefa35b661bd7b34517'), source, summary:'Lee un botón físico y toma tu primera decisión.', steps:['Mira el video oficial del sensor de contacto.', 'Conecta el sensor EV3 de contacto al puerto 3.', 'Inserta Sensor de contacto y observa 0 o 1 en la consola.', 'Usa if (await robot.sensor(3, "touch")) para reproducir un tono al presionar.'], challenge:'Lee el botón cinco veces y muestra un mensaje diferente al presionarlo.' },
  { id:'color', title:'Descubre los colores', label:'Sensores', time:'25 min', color:'purple', video:video('38679782','da35bb9e3bab736b632c7bbc8e5ab555'), source, summary:'Reconoce colores o mide luz reflejada.', steps:['Mira el video oficial del sensor de color.', 'Conecta el sensor EV3 de color al puerto 2 y acércalo a una pieza.', 'Inserta Sensor de color. La lectura identifica colores con números de 0 a 7.', 'Cambia "color" por "reflection" para leer luz reflejada de 0 a 100.'], challenge:'Compara una superficie clara con una oscura y registra cinco lecturas.' },
  { id:'distance', title:'Detecta un obstáculo', label:'Distancia', time:'30 min', color:'blue', video:video('38683781','e5a2d5dd0a164a0611a4f2285039c4f6'), source, summary:'Mide distancia con el sensor ultrasónico EV3.', steps:['Mira el video oficial del sensor ultrasónico.', 'Conecta el sensor ultrasónico EV3 al puerto 1.', 'Inserta Sensor de distancia: el resultado está en centímetros.', 'Acerca un objeto y compara las lecturas. El sensor infrarrojo usa "infrared" y proximidad relativa, no centímetros.'], challenge:'Reproduce un tono cuando un objeto esté a menos de 15 cm.' },
];
